[package]
name = "backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = "1.0"
rocket = "0.5.0-rc.2"
bb8 = "0.8"
bb8-postgres = "0.8.1"
tokio-postgres = "0.7.7"